'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActividadesObras
    Public Property Id As Integer
    Public Property GestionObraId As Integer
    Public Property Fecha As Date
    Public Property Motivo As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property GestionObras As GestionObras

End Class
