'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditoriaDocumentos
    Public Property Id As Integer
    Public Property FechaEliminacion As Nullable(Of Date)
    Public Property UsuarioResponsable As String
    Public Property MotivoEliminacion As String
    Public Property DocIdOriginal As Nullable(Of Integer)
    Public Property DocReferencia As String
    Public Property DocAsunto As String
    Public Property DocFechaCarga As Nullable(Of Date)

    Public Overridable Property AuditoriaMovimientos As ICollection(Of AuditoriaMovimientos) = New HashSet(Of AuditoriaMovimientos)

End Class
