'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditoriaMovimientos
    Public Property Id As Integer
    Public Property AuditoriaDocId As Integer
    Public Property FechaMovimientoOriginal As Nullable(Of Date)
    Public Property Origen As String
    Public Property Destino As String
    Public Property TipoMovimiento As String
    Public Property Observaciones As String

    Public Overridable Property AuditoriaDocumentos As AuditoriaDocumentos

End Class
