'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CandidatosLaborales
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property IdoneidadId As Integer
    Public Property FechaVencimientoPena As Nullable(Of Date)
    Public Property FechaTercioPena As Nullable(Of Date)
    Public Property Estado As String
    Public Property Observaciones As String

    Public Overridable Property Idoneidades As Idoneidades
    Public Overridable Property Reclusos As Reclusos

End Class
