'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comisiones
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property TareaId As Integer
    Public Property NumeroTarjeta As Nullable(Of Integer)
    Public Property FechaInicio As Date
    Public Property FechaFin As Nullable(Of Date)
    Public Property Horario As String
    Public Property Activa As Nullable(Of Boolean)
    Public Property MotivoAlta As String
    Public Property MotivoBaja As String
    Public Property Observaciones As String

    Public Overridable Property Reclusos As Reclusos
    Public Overridable Property Tareas As Tareas

End Class
