'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comunicados
    Public Property Id As Integer
    Public Property Fecha As Date
    Public Property Asunto As String
    Public Property Destino As String
    Public Property Directivas As String
    Public Property Numero As Nullable(Of Integer)

End Class
