'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Documentos
    Public Property Id As Integer
    Public Property ReclusoId As Nullable(Of Integer)
    Public Property TipoDocumentoId As Integer
    Public Property Descripcion As String
    Public Property Contenido As Byte()
    Public Property NombreArchivo As String
    Public Property Extension As String
    Public Property FechaCarga As Nullable(Of Date)
    Public Property ReferenciaExterna As String

    Public Overridable Property Reclusos As Reclusos
    Public Overridable Property TiposDocumento As TiposDocumento
    Public Overridable Property MovimientosDocumentos As ICollection(Of MovimientosDocumentos) = New HashSet(Of MovimientosDocumentos)

End Class
