'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DocumentoVinculos
    Public Property Id As Integer
    Public Property IdDocumentoPadre As Integer
    Public Property IdDocumentoHijo As Integer
    Public Property TipoRelacion As String
    Public Property FechaVinculo As Nullable(Of Date)

    Public Overridable Property Documentos As Documentos
    Public Overridable Property Documentos1 As Documentos

End Class
