'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estados
    Public Property Id As Integer
    Public Property Descripcion As String

    Public Overridable Property Obras As ICollection(Of Obras) = New HashSet(Of Obras)
    Public Overridable Property Reclusos As ICollection(Of Reclusos) = New HashSet(Of Reclusos)

End Class
