'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventosSistema
    Public Property Id As Integer
    Public Property Fecha As Nullable(Of Date)
    Public Property Descripcion As String
    Public Property UsuarioId As Integer

    Public Overridable Property Usuarios As Usuarios

End Class
