'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GestionObras
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property ObraId As Integer
    Public Property FechaAlta As Date
    Public Property Autorizado As Nullable(Of Boolean)
    Public Property Activo As Nullable(Of Boolean)
    Public Property NumeroActa As String

    Public Overridable Property ActividadesObras As ICollection(Of ActividadesObras) = New HashSet(Of ActividadesObras)
    Public Overridable Property Obras As Obras
    Public Overridable Property Reclusos As Reclusos

End Class
