'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Licencias
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property MotivoAusenciaId As Integer
    Public Property FechaInicio As Date
    Public Property FechaFin As Date
    Public Property Detalles As String

    Public Overridable Property MotivosAusencia As MotivosAusencia
    Public Overridable Property Reclusos As Reclusos

End Class
