'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PoloNuevoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PoloNuevoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AuditoriaDocumentos() As DbSet(Of AuditoriaDocumentos)
    Public Overridable Property AuditoriaMovimientos() As DbSet(Of AuditoriaMovimientos)
    Public Overridable Property Comunicados() As DbSet(Of Comunicados)
    Public Overridable Property Documentos() As DbSet(Of Documentos)
    Public Overridable Property DocumentoVinculos() As DbSet(Of DocumentoVinculos)
    Public Overridable Property Estados() As DbSet(Of Estados)
    Public Overridable Property EventosSistema() As DbSet(Of EventosSistema)
    Public Overridable Property MotivosAusencia() As DbSet(Of MotivosAusencia)
    Public Overridable Property MovimientosDocumentos() As DbSet(Of MovimientosDocumentos)
    Public Overridable Property NumeracionRangos() As DbSet(Of NumeracionRangos)
    Public Overridable Property TiposDocumento() As DbSet(Of TiposDocumento)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property vw_DocumentosDetalle() As DbSet(Of vw_DocumentosDetalle)
    Public Overridable Property vw_PlanillaMensual() As DbSet(Of vw_PlanillaMensual)
    Public Overridable Property vw_ReclusosMaestro() As DbSet(Of vw_ReclusosMaestro)

End Class
