'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PoloNuevoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PoloNuevoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ActividadesObras() As DbSet(Of ActividadesObras)
    Public Overridable Property CandidatosLaborales() As DbSet(Of CandidatosLaborales)
    Public Overridable Property Comisiones() As DbSet(Of Comisiones)
    Public Overridable Property Comunicados() As DbSet(Of Comunicados)
    Public Overridable Property Documentos() As DbSet(Of Documentos)
    Public Overridable Property Estados() As DbSet(Of Estados)
    Public Overridable Property EventosSistema() As DbSet(Of EventosSistema)
    Public Overridable Property GestionObras() As DbSet(Of GestionObras)
    Public Overridable Property Idoneidades() As DbSet(Of Idoneidades)
    Public Overridable Property Licencias() As DbSet(Of Licencias)
    Public Overridable Property MotivosAusencia() As DbSet(Of MotivosAusencia)
    Public Overridable Property MovimientosDocumentos() As DbSet(Of MovimientosDocumentos)
    Public Overridable Property Notificaciones() As DbSet(Of Notificaciones)
    Public Overridable Property Obras() As DbSet(Of Obras)
    Public Overridable Property PlanillasLaborales() As DbSet(Of PlanillasLaborales)
    Public Overridable Property Reclusos() As DbSet(Of Reclusos)
    Public Overridable Property SalidasTransitorias() As DbSet(Of SalidasTransitorias)
    Public Overridable Property Tareas() As DbSet(Of Tareas)
    Public Overridable Property Tarjetas() As DbSet(Of Tarjetas)
    Public Overridable Property TiposDocumento() As DbSet(Of TiposDocumento)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property VencimientosLegales() As DbSet(Of VencimientosLegales)
    Public Overridable Property vw_ReclusosMaestro() As DbSet(Of vw_ReclusosMaestro)
    Public Overridable Property vw_DocumentosDetalle() As DbSet(Of vw_DocumentosDetalle)
    Public Overridable Property vw_PlanillaMensual() As DbSet(Of vw_PlanillaMensual)
    Public Overridable Property AuditoriaDocumentos() As DbSet(Of AuditoriaDocumentos)
    Public Overridable Property AuditoriaMovimientos() As DbSet(Of AuditoriaMovimientos)
    Public Overridable Property NumeracionRangos() As DbSet(Of NumeracionRangos)
    Public Overridable Property DocumentoVinculos() As DbSet(Of DocumentoVinculos)

End Class
