'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimientosDocumentos
    Public Property Id As Integer
    Public Property DocumentoId As Integer
    Public Property FechaMovimiento As Date
    Public Property Origen As String
    Public Property Destino As String
    Public Property EsSalida As Boolean
    Public Property Observaciones As String

    Public Overridable Property Documentos As Documentos

End Class
