'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NumeracionRangos
    Public Property Id As Integer
    Public Property TipoDocumentoId As Integer
    Public Property NombreRango As String
    Public Property NumeroInicio As Integer
    Public Property NumeroFin As Integer
    Public Property UltimoUtilizado As Integer
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property TiposDocumento As TiposDocumento

End Class
