'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Obras
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property EstadoId As Integer

    Public Overridable Property Estados As Estados
    Public Overridable Property GestionObras As ICollection(Of GestionObras) = New HashSet(Of GestionObras)

End Class
