'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PlanillasLaborales
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property TareaId As Integer
    Public Property Mes As Integer
    Public Property Anio As Integer
    Public Property DiasTrabajados As Integer
    Public Property CargaHoraria As Integer
    Public Property TotalHoras As Integer
    Public Property Remuneracion As String
    Public Property Observaciones As String

    Public Overridable Property Reclusos As Reclusos
    Public Overridable Property Tareas As Tareas

End Class
