'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reclusos
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Cedula As Integer
    Public Property Modulo As Integer
    Public Property FechaNacimiento As Date
    Public Property Peculio As String
    Public Property EstadoId As Integer
    Public Property FechaRegistro As Nullable(Of Date)

    Public Overridable Property CandidatosLaborales As ICollection(Of CandidatosLaborales) = New HashSet(Of CandidatosLaborales)
    Public Overridable Property Comisiones As ICollection(Of Comisiones) = New HashSet(Of Comisiones)
    Public Overridable Property Documentos As ICollection(Of Documentos) = New HashSet(Of Documentos)
    Public Overridable Property Estados As Estados
    Public Overridable Property GestionObras As ICollection(Of GestionObras) = New HashSet(Of GestionObras)
    Public Overridable Property Licencias As ICollection(Of Licencias) = New HashSet(Of Licencias)
    Public Overridable Property Notificaciones As ICollection(Of Notificaciones) = New HashSet(Of Notificaciones)
    Public Overridable Property PlanillasLaborales As ICollection(Of PlanillasLaborales) = New HashSet(Of PlanillasLaborales)
    Public Overridable Property Tarjetas As ICollection(Of Tarjetas) = New HashSet(Of Tarjetas)
    Public Overridable Property SalidasTransitorias As ICollection(Of SalidasTransitorias) = New HashSet(Of SalidasTransitorias)
    Public Overridable Property VencimientosLegales As ICollection(Of VencimientosLegales) = New HashSet(Of VencimientosLegales)

End Class
