'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalidasTransitorias
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property FechaSolicitud As Date
    Public Property TipoTransitoria As String
    Public Property Domicilio As String
    Public Property NombreTutor As String
    Public Property TelefonoContacto As String
    Public Property EstadoSolicitud As String

    Public Overridable Property Reclusos As Reclusos

End Class
