'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tareas
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property EsTareaPrimaria As Nullable(Of Boolean)

    Public Overridable Property Comisiones As ICollection(Of Comisiones) = New HashSet(Of Comisiones)
    Public Overridable Property PlanillasLaborales As ICollection(Of PlanillasLaborales) = New HashSet(Of PlanillasLaborales)

End Class
