'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tarjetas
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property NumeroTarjeta As Integer
    Public Property FechaHoraInicio As Date
    Public Property FechaHoraFin As Nullable(Of Date)

    Public Overridable Property Reclusos As Reclusos

End Class
