'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VencimientosLegales
    Public Property Id As Integer
    Public Property ReclusoId As Integer
    Public Property FechaVencimientoPena As Nullable(Of Date)
    Public Property FechaInformeOperativo As Nullable(Of Date)
    Public Property FechaEntrevista As Nullable(Of Date)
    Public Property FechaOasys As Nullable(Of Date)

    Public Overridable Property Reclusos As Reclusos

End Class
