'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_DocumentosDetalle
    Public Property Id As Integer
    Public Property ReclusoId As Nullable(Of Integer)
    Public Property Tipo As String
    Public Property Descripcion As String
    Public Property FechaCarga As Nullable(Of Date)
    Public Property Extension As String
    Public Property Formato As String
    Public Property NombreArchivo As String

End Class
