'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PlanillaMensual
    Public Property Id As Integer
    Public Property Recluso As String
    Public Property Cedula As Integer
    Public Property Tarea As String
    Public Property Mes As Integer
    Public Property Anio As Integer
    Public Property DiasTrabajados As Integer
    Public Property TotalHoras As Integer
    Public Property Observaciones As String

End Class
