'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_ReclusosMaestro
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Cedula As Integer
    Public Property Modulo As Integer
    Public Property Estado As String
    Public Property FechaNacimiento As Date
    Public Property Edad As Nullable(Of Integer)
    Public Property Peculio As String
    Public Property CantDocumentos As Nullable(Of Integer)
    Public Property SituacionLaboral As String

End Class
